<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>pscanner</AssemblyName>
		<PackAsTool>true</PackAsTool>
		<ToolCommandName>pscanner</ToolCommandName>
		<PackageId>pscanner</PackageId>
		<Version>1.0.0</Version>
	</PropertyGroup>
</Project>